apiVersion: v1
kind: Service
metadata:
  labels:
    name: block-stream-1
  name: block-stream-1
spec:
  selector:
    app: api-1
  ports:
    - name: block-stream
      protocol: TCP
      port: 9010
      targetPort: 9010