apiVersion: v1
kind: Service
metadata:
  labels:
    name: block-stream-0
  name: block-stream-0
spec:
  selector:
    app: api-0
  ports:
    - name: block-stream
      protocol: TCP
      port: 9010
      targetPort: 9010