apiVersion: v1
kind: Service
metadata:
  labels:
    name: block-stream-2
  name: block-stream-2
spec:
  selector:
    app: api-2
  ports:
    - name: block-stream
      protocol: TCP
      port: 9010
      targetPort: 9010