apiVersion: v1
kind: Service
metadata:
  labels:
    name: block-stream-4
  name: block-stream-4
spec:
  selector:
    app: api-4
  ports:
    - name: block-stream
      protocol: TCP
      port: 9010
      targetPort: 9010