apiVersion: v1
kind: Service
metadata:
  labels:
    name: postgresdb-service-0
    app: postgres-db-0
  name: postgresdb-service-0
spec:
  ports:
    - name: pg-port
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
     app: postgres-db-0
