apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator-pbft-0
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: validator-pbft-0
  template:
    metadata:
      labels:
        app: validator-pbft-0
    spec:
      containers:
        # Validator
        - name: validator
          image: hyperledger/sawtooth-validator:chime
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 250m
              memory: 1Gi
          ports:
            - name: tp
              containerPort: 4004
            - name: validators
              containerPort: 8800
            - name: consensus
              containerPort: 5050
          envFrom:
            - configMapRef:
                name: keys-config
          command:
            - bash
          args:
            - -c
            - |
              if [ ! -e /etc/sawtooth/keys/validator.priv ]; then
                echo $pbft0priv > /etc/sawtooth/keys/validator.priv
                echo $pbft0pub > /etc/sawtooth/keys/validator.pub
              fi &&
              if [ ! -e /root/.sawtooth/keys/my_key.priv ]; then
                sawtooth keygen my_key
              fi &&
              if [ ! -e config-genesis.batch ]; then
                sawset genesis -k /root/.sawtooth/keys/my_key.priv -o config-genesis.batch
              fi &&
              sleep 30 &&
              echo sawtooth.consensus.pbft.members=["\"$pbft0pub\",\"$pbft1pub\",\"$pbft2pub\",\"$pbft3pub\",\"$pbft4pub\""] &&
              if [ ! -e config.batch ]; then
                sawset proposal create \
                    -k /root/.sawtooth/keys/my_key.priv \
                    sawtooth.consensus.algorithm.name=pbft \
                    sawtooth.consensus.algorithm.version=1.0\
                    sawtooth.consensus.pbft.members=["\"$pbft0pub\",\"$pbft1pub\",\"$pbft2pub\",\"$pbft3pub\",\"$pbft4pub\""] \
                    sawtooth.publisher.max_batches_per_block=1200 \
                    -o config.batch
              fi && \
              if [ ! -s /var/lib/sawtooth/backup/backupdata ]; then
                sawadm genesis config-genesis.batch config.batch;
              else
                sawadm blockstore restore /var/lib/sawtooth/backup/backupdata
              fi &&
              sawtooth-validator -vv \
                  --endpoint tcp://validator-pbft-0:8800 \
                  --bind component:tcp://0.0.0.0:4004 \
                  --bind consensus:tcp://0.0.0.0:5050 \
                  --bind network:tcp://0.0.0.0:8800 \
                  --scheduler parallel \
                  --peering static \
                  --maximum-peer-connectivity 10000
        
        # PBFT Engine
        - name: sawtooth-pbft-engine
          image: hyperledger/sawtooth-pbft-engine:chime
          resources:
            limits:
              cpu: 100m
              memory: 250Mi
            requests:
              cpu: 50m
              memory: 100Mi
          command:
            - bash
          args:
            - -c
            - "pbft-engine -vv --connect tcp://$HOSTNAME:5050"

        # Settings-TP
        - name: settings-tp
          image: hyperledger/sawtooth-settings-tp:chime
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 250Mi
            requests:
              cpu: 50m
              memory: 100Mi
          ports:
            - name: validator
              containerPort: 4004
          command:
            - bash
          args:
            - -c
            - "settings-tp -vv -C tcp://$HOSTNAME:4004"

        # Sawtooth REST API
        - name: sawtooth-rest-api
          image: hyperledger/sawtooth-rest-api:chime
          resources:
            limits:
              cpu: 100m
              memory: 250Mi
            requests:
              cpu: 50m
              memory: 100Mi
          ports:
            - name: api
              containerPort: 8008
          command:
            - bash
          args:
            - -c
            - "sawtooth-rest-api -vv -C tcp://$HOSTNAME:4004 -B 0.0.0.0:8008"
          # readinessProbe:
          #   httpGet:
          #     path: /status
          #     port: 8008
          #   initialDelaySeconds: 15
          #   periodSeconds: 10
